# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/labeling_test',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/labeling_test',
                'lib_path': 'labeling_test'},
  'syms': {'labeling_test.core': {'labeling_test.core.foo': ('core.html#foo', 'labeling_test/core.py')}}}
