# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_Idefics2.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/06_Idefics2.ipynb 4
import requests
import torch
from PIL import Image

from transformers import AutoProcessor, AutoModelForVision2Seq
from transformers.image_utils import load_image

# %% ../nbs/06_Idefics2.ipynb 5
from cv_tools.core import *
