# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_tile.ipynb.

# %% auto 0
__all__ = ['process_tile']

# %% ../nbs/03_tile.ipynb 2
import torch
import torch.nn.functional as F

# %% ../nbs/03_tile.ipynb 4
# function to  process a tile
def process_tile(tile, kernel, bias):
    # apply convolution to the tile
    return F.conv2d(tile, kernel, bias, (1, 1), (1,1), (1,1),1)
